server:
  port: 8889
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
  instance:
    leaseRenewalIntervalInSeconds: 10




  
  

      
